@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1>Admission Masterlist</h1><p>{{ $cycle->name }}</p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="{{ route('admin.admission.index') }}">Configuration</a><a class="btn btn-outline-primary" href="{{ route('admin.admission.scan-paper') }}">Scan paper</a><a class="btn btn-primary" href="{{ route('admin.admission.masterlist', request()->query()) }}">Refresh Data</a></div></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif @if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if(session('import_errors'))<div class="alert alert-warning">{{ implode('; ', session('import_errors')) }}</div>@endif
<div class="card page-card mb-3"><div class="card-body"><div class="row g-3"><div class="col-md-6"><h2 class="h5">Import applicants</h2><form method="post" enctype="multipart/form-data" action="{{ route('admin.admission.applicants.import') }}" class="d-flex gap-2">@csrf<input type="file" name="file" accept=".csv,.xlsx" class="form-control" required><button class="btn btn-primary">Import</button></form><small>CSV/XLSX columns: student_id, first_name, middle_name, last_name, course, sex, 4ps_osy_ip_pwd_sp, cmfl, gwa</small></div><div class="col-md-6"><h2 class="h5">Reports</h2><form method="get" action="{{ route('admin.admission.report') }}" class="d-flex gap-2"><select name="type" class="form-select"><option value="summary">Evaluation summary</option><option value="qualified">Qualified</option><option value="not-qualified">Non-qualified</option></select><select name="course" class="form-select"><option value="">All courses</option>@foreach($courses as $code=>$title)<option value="{{ $code }}">{{ $code }}</option>@endforeach</select><select name="format" class="form-select"><option value="html">Print</option><option value="pdf">PDF</option><option value="docx">DOCX</option></select><button class="btn btn-primary">Open</button></form></div></div></div></div>
<div class="card page-card mb-3"><div class="card-body"><h2 class="h5">Add applicant</h2><form method="post" action="{{ route('admin.admission.applicants.save') }}" class="row g-2">@csrf @include('admin.admission.fields', ['applicant'=>null])<div class="col-12"><button class="btn btn-primary">Save applicant</button></div></form></div></div>
<div class="card page-card"><div class="card-body"><form method="get" class="d-flex gap-2 mb-3"><input name="search" value="{{ $search }}" class="form-control" placeholder="Search number or surname"><button class="btn btn-outline-primary">Search</button></form><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Number</th><th>Applicant</th><th>Course</th><th>GWA</th><th>Exam</th><th>Stanine</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>@forelse($applicants as $applicant)<tr><td>{{ $applicant->application_number }}</td><td>{{ $applicant->full_name }}</td><td>{{ $applicant->course_choice }}</td><td>{{ $applicant->gwa }}</td><td>{{ $applicant->exam_score ?? '—' }}</td><td>{{ $applicant->stanine_score ?? '—' }}</td><td>{{ $applicant->total_score ?? '—' }}</td><td><span class="badge bg-{{ $applicant->qualification_status==='Qualified'?'success':($applicant->qualification_status==='Pending'?'secondary':'danger') }}">{{ $applicant->qualification_status }}</span></td><td><button class="btn btn-sm btn-outline-primary" data-bs-toggle="modal" data-bs-target="#edit-{{ $applicant->id }}">Edit</button><a class="btn btn-sm btn-outline-primary" href="{{ route('admin.admission.paper', $applicant) }}">Paper</a>@unless($applicant->submitted_at)<form class="d-inline" method="post" action="{{ route('admin.admission.applicants.token',$applicant) }}">@csrf<button class="btn btn-sm btn-outline-secondary">Issue exam link</button></form>@endunless</td></tr>
<div class="modal fade" id="edit-{{ $applicant->id }}" tabindex="-1"><div class="modal-dialog modal-lg"><div class="modal-content"><div class="modal-header"><h2 class="modal-title h5">Edit applicant</h2><button class="btn-close" data-bs-dismiss="modal"></button></div><form method="post" action="{{ route('admin.admission.applicants.save',$applicant) }}"><div class="modal-body row g-2">@csrf @include('admin.admission.fields', ['applicant'=>$applicant])<div class="col-md-4"><label class="form-label">Computed exam score</label><input value="{{ $applicant->exam_score ?? 'Not submitted' }}" class="form-control" disabled readonly></div></div><div class="modal-footer"><button class="btn btn-primary">Save details</button></div></form></div></div></div>
@empty<tr><td colspan="9" class="text-center">No applicants yet.</td></tr>@endforelse</tbody></table></div>{{ $applicants->links() }}</div></div>
@endsection
