@extends('layouts.app')
@section('content')
<div class="d-flex justify-content-between align-items-center mb-3"><div><h1>PSU-CAT Admission</h1><p class="text-muted">Configure the active admission cycle before encoding or reporting.</p></div><div class="d-flex gap-2"><a class="btn btn-outline-primary" href="{{ route('admin.admission.proctoring') }}">Proctoring</a>@if($active)<a class="btn btn-primary" href="{{ route('admin.admission.masterlist') }}">Open Masterlist</a>@endif</div></div>
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card page-card mb-4"><div class="card-body"><h2 class="h5">Create admission cycle</h2><form method="post" action="{{ route('admin.admission.cycles.save') }}" class="row g-2">@csrf
<div class="col-md-3"><label class="form-label">Cycle name</label><input name="name" class="form-control" placeholder="S.Y. 2025 - 2026" required></div>
<div class="col-md-2"><label class="form-label">Academic year</label><input name="academic_year" class="form-control" placeholder="2025-2026" required></div>
<div class="col-md-2"><label class="form-label">Passing stanine</label><input type="number" name="passing_stanine" value="4" min="1" max="9" class="form-control"></div>
<div class="col-md-1"><label class="form-label">Exam %</label><input type="number" name="exam_weight" value="60" class="form-control"></div>
<div class="col-md-1"><label class="form-label">GWA %</label><input type="number" name="gwa_weight" value="20" class="form-control"></div>
<div class="col-md-1"><label class="form-label">Interview %</label><input type="number" name="interview_weight" value="20" class="form-control"></div>
<div class="col-md-2 d-flex align-items-end"><button class="btn btn-primary w-100">Save cycle</button></div></form></div></div>
<div class="card page-card mb-4"><div class="card-body"><h2 class="h5">Cycles</h2><div class="table-responsive"><table class="table table-sm align-middle"><thead><tr><th>Cycle</th><th>Year</th><th>Stanine</th><th>Status</th><th>Actions</th></tr></thead><tbody>@foreach($cycles as $cycle)<tr><td>{{ $cycle->name }}</td><td>{{ $cycle->academic_year }}</td><td>{{ $cycle->passing_stanine }}</td><td>{{ $cycle->is_archived ? 'Archived' : ($cycle->is_active ? 'Active' : 'Inactive') }}</td><td class="d-flex gap-2">@unless($cycle->is_archived)<form method="post" action="{{ route('admin.admission.cycles.activate', $cycle) }}">@csrf<button class="btn btn-sm btn-outline-primary">Activate</button></form><form method="post" action="{{ route('admin.admission.cycles.archive', $cycle) }}" onsubmit="return confirm('Archive this cycle?')">@csrf<button class="btn btn-sm btn-outline-secondary">Archive</button></form><button class="btn btn-sm btn-outline-primary" data-bs-toggle="collapse" data-bs-target="#cycle-{{ $cycle->id }}">Edit</button>@endunless</td></tr><tr class="collapse" id="cycle-{{ $cycle->id }}"><td colspan="5"><form method="post" action="{{ route('admin.admission.cycles.save', $cycle) }}" class="row g-2">@csrf <div class="col"><input name="name" value="{{ $cycle->name }}" class="form-control" required></div><div class="col"><input name="academic_year" value="{{ $cycle->academic_year }}" class="form-control" required></div><div class="col"><input type="number" name="passing_stanine" value="{{ $cycle->passing_stanine }}" min="1" max="9" class="form-control"></div><div class="col"><input type="number" name="exam_weight" value="{{ $cycle->exam_weight }}" class="form-control"></div><div class="col"><input type="number" name="gwa_weight" value="{{ $cycle->gwa_weight }}" class="form-control"></div><div class="col"><input type="number" name="interview_weight" value="{{ $cycle->interview_weight }}" class="form-control"></div><div class="col"><button class="btn btn-primary">Save</button></div></form></td></tr>@endforeach</tbody></table></div></div></div>
@if($active)<div class="row g-3"><div class="col-lg-4"><div class="card page-card h-100"><div class="card-body"><h2 class="h5">Seat quotas</h2><form method="post" action="{{ route('admin.admission.quotas.save') }}">@csrf <select name="course_code" class="form-select mb-2" required>@foreach($courses as $code=>$title)<option value="{{ $code }}">{{ $code }} — {{ $title }}</option>@endforeach</select><input type="number" min="0" name="seats" class="form-control mb-2" placeholder="Seats" required><button class="btn btn-primary">Save quota</button></form></div></div></div><div class="col-lg-8"><div class="card page-card"><div class="card-body"><h2 class="h5">Answer key (80 items)</h2><form method="post" action="{{ route('admin.admission.answer-key.save') }}">@csrf<div class="row g-2" style="max-height:330px;overflow:auto">@php($keys=\Illuminate\Support\Facades\DB::table('admission_answer_keys')->where('admission_cycle_id',$active->id)->pluck('correct_answer','item_number'))@for($i=1;$i<=80;$i++)<div class="col-6 col-md-3"><label class="form-label">{{ $i }}</label><select name="answers[{{ $i }}]" class="form-select form-select-sm" required><option value="">Choose</option>@foreach(['A','B','C','D'] as $letter)<option value="{{ $letter }}" @selected(($keys[$i]??null)===$letter)>{{ $letter }}</option>@endforeach</select></div>@endfor</div><button class="btn btn-primary mt-3">Save answer key</button></form></div></div></div></div>@endif
@endsection
